"""empty message

Revision ID: dcdeb60c63b9
Revises: 
Create Date: 2018-12-14 01:28:02.826829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdeb60c63b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputadof',
    sa.Column('id_deputadof', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('nome_civil', sa.String(), nullable=True),
    sa.Column('nome_eleitoral', sa.String(), nullable=True),
    sa.Column('sigla_partido', sa.String(), nullable=True),
    sa.Column('uri_partido', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('id_legislatura', sa.Integer(), nullable=True),
    sa.Column('data_inicio_mandato', sa.String(), nullable=True),
    sa.Column('url_foto', sa.String(), nullable=True),
    sa.Column('end_predio', sa.String(), nullable=True),
    sa.Column('end_sala', sa.String(), nullable=True),
    sa.Column('end_andar', sa.String(), nullable=True),
    sa.Column('end_telefone', sa.String(), nullable=True),
    sa.Column('end_email', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('condicao_eleitoral', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.String(), nullable=True),
    sa.Column('uf_nascimento', sa.String(), nullable=True),
    sa.Column('municipio_nascimento', sa.String(), nullable=True),
    sa.Column('escolaridade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_deputadof')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deputadof_id', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('tipo_despesa', sa.String(), nullable=True),
    sa.Column('id_documento', sa.Integer(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=True),
    sa.Column('data_documento', sa.String(), nullable=True),
    sa.Column('numero_documento', sa.Integer(), nullable=True),
    sa.Column('valor_documento', sa.Integer(), nullable=True),
    sa.Column('nome_fornecedor', sa.String(), nullable=True),
    sa.Column('cnpj_cpf_fornecedor', sa.String(), nullable=True),
    sa.Column('valor_liquido', sa.Integer(), nullable=True),
    sa.Column('valor_glosa', sa.Integer(), nullable=True),
    sa.Column('numero_ressarcimento', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('parcela', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deputadof_id'], ['deputadof.id_deputadof'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    op.drop_table('deputadof')
    # ### end Alembic commands ###
